apiVersion: halkyon.io/v1beta1
kind: Component
metadata:
  name: module-dummypom
spec:
  deploymentMode: build
  port: 8080
  buildConfig:
    type: s2i
    url: https://github.com/rhte-eu/cmoullia.git
    ref: dummypom
    moduleDirName: fruit-client-sb
  runtime: spring-boot
  version: 2.1.6