apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hal
  name: hal
spec:
  containers:
    - command:
        - /var/lib/supervisord/bin/supervisord
      args:
        - '-c'
        - /var/lib/supervisord/conf/supervisor.conf
      image: 'quay.io/halkyonio/hal-maven-jdk'
      imagePullPolicy: Always
      name: simple
      env:
      - name: MAVEN_ARGS
        value:
      - name: CONTEXTPATH
        value: .
      - name: MODULEDIRNAME
        value: .
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      securityContext:
        capabilities:
          drop:
            - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/lib/supervisord
          name: shared-data
  initContainers:
    - env:
        - name: CMDS
          value: >-
            run:/usr/local/bin/run:true;build:/usr/local/bin/build:false
      image: 'quay.io/halkyonio/supervisord:latest'
      imagePullPolicy: Always
      name: copy-supervisord
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/lib/supervisord
          name: shared-data
  serviceAccount: default
  volumes:
    - emptyDir: {}
      name: shared-data
