apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fruit-client-sb
    component_cr: fruit-client-sb
    deployment: fruit-client-sb
  name: m2-data-fruit-client-sb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
