---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m2-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: supervisord-test
  labels:
    app: fruit-client
spec:
  containers:
  - args:
    - '-c'
    - /var/lib/supervisord/conf/supervisor.conf
    command:
    - /var/lib/supervisord/bin/supervisord
    env:
    - name: JAVA_APP_DIR
      value: /deployments
    image: quay.io/halkyonio/openjdk8-s2i:latest
    imagePullPolicy: Always
    name: fruit-client
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
    - mountPath: /var/lib/supervisord
      name: shared-data
    - mountPath: /tmp/artifacts
      name: m2-data
  initContainers:
  - env:
    - name: CMDS
      value: "run-java:/usr/local/s2i/run;appcheck:/var/lib/supervisord/bin/appcheck;compile-java:/usr/local/s2i/assemble"
    image: quay.io/halkyonio/supervisord:test
    imagePullPolicy: Always
    name: copy-supervisord
    volumeMounts:
    - mountPath: /var/lib/supervisord
      name: shared-data
  volumes:
  - emptyDir: {}
    name: shared-data
  - name: m2-data
    persistentVolumeClaim:
      claimName: m2-data