version: 2.1

jobs:
  k8s:
    docker:
      - image: circleci/golang:1.12.7

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run:
          name: Install k8s
          command: |
            GO111MODULE="on" go get sigs.k8s.io/kind@v0.4.0
      - run:
          name: Create Kibnd cluster
          command: |
            kind create cluster --name circleci

      - run:
          name: Get k8s config
          command: |
            export KUBECONFIG="$(kind get kubeconfig-path)"
            kubectl cluster-info

workflows:
  version: 2
  k8s-centos:
    jobs:
      - k8s

