version: 2.1

jobs:
  build:
    docker:
      - image: docker:17.06.0-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            cd circleci
            docker build -t quay.io/snowdrop/centos-circleci .
      #- deploy:
      #    name: Tag docker images
      #    command: |
      #      docker tag scholzj/circleci-centos-golang:circle docker.io/scholzj/circleci-centos-golang:centos7-go1.10.0
      #      docker tag scholzj/circleci-centos-golang:circle docker.io/scholzj/circleci-centos-golang:latest
      - deploy:
          name: Login to Quay Hub
          command: docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
      - deploy:
          name: Push docker images
          command: |
            docker push quay.io/snowdrop/centos-circleci
  k8s:
    docker:
      - image: circleci/golang:1.12.7

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install k8s
          command: |
            GO111MODULE="on" go get sigs.k8s.io/kind@v0.4.0
      - run:
          name: Create Kibnd cluster
          command: |
            docker ps
            kind create cluster --image=kindest/node:v1.14.3 --name circleci --loglevel=debug

      - run:
          name: Get k8s config
          command: |
            export KUBECONFIG="$(kind get kubeconfig-path)"
            kubectl cluster-info

workflows:
  version: 2
  k8s-centos:
    jobs:
      - build
      - k8s:
          requires:
            - build

