version: 2.1

jobs:
  test:
    machine:
      image: quay.io/snowdrop/centos-circleci
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hi"
  build:
    docker:
      - image: docker:17.06.0-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: |
            cd circleci
            docker build -t quay.io/snowdrop/centos-circleci .
      - deploy:
          name: Login to Quay Hub
          command: docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
      - deploy:
          name: Push docker images
          command: |
            docker push quay.io/snowdrop/centos-circleci

workflows:
  version: 2
  k8s-centos:
    jobs:
      - test

